### PR TITLE
Resolve #99: Fix abigen with int expression template arguments

### LINKED ISSUE #99: abigen fails on int-expression template arguments
In my contracts, I use several template arguments which are expressions which resolve to integral values (such as an `eosio::name`) but are not literal integer values. This works great in my contracts, but causes abigen to fail.

### PR DESCRIPTION
**Pull request by nathanielhourt**
## Change Description
Resolve #99
In my contracts, I use several template arguments which are expressions which resolve to integral values (such as an `eosio::name`) but are not literal integer values. This works great in my contracts, but causes abigen to fail.

This PReq fixes abigen in such cases where a template argument is an expression that resolves to an integer, but isn't an integer literal.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by nathanielhourt** [comment]
Historical note: This PReq is identical to [eosio.cdt#1250](https://github.com/EOSIO/eosio.cdt/pull/1250).

File: tools/include/eosio/gen.hpp [hunk 1]
```diff
@@ -370,7 +370,8 @@ struct generation_utils {
          if (auto ce = llvm::dyn_cast<clang::CastExpr>(std::get<clang::Expr*>(arg))) {
             auto il = llvm::dyn_cast<clang::IntegerLiteral>(ce->getSubExpr());
             return std::to_string(il->getValue().getLimitedValue());
-         }
+         } else if (auto ce = llvm::dyn_cast<clang::ConstantExpr>(std::get<clang::Expr*>(arg)))
+             return ce->getResultAsAPSInt().toString(10);
```
Comment (ScottBailey) [inline tools/include/eosio/gen.hpp:374]: Feels like some extra brackets would improve readability and match the style of the code block around it.

```suggestion
         } else if (auto ce = llvm::dyn_cast<clang::ConstantExpr>(std::get<clang::Expr*>(arg))) {
             return ce->getResultAsAPSInt().toString(10);
         }
```

**Review by dimas1185 — CHANGES_REQUESTED** [review]
looks good. please add a test to `tests/abigen-pass` directory. look at other examples, there are small *.json, *.abi and *.cpp to demonstrate how this works

**Comment by nathanielhourt** [comment]
Good call. Added a test which fails before the fix, and passes after.

**Review by dimas1185 — APPROVED** [review]

**Review by ScottBailey — APPROVED** [review]
